### ISSUE TITLE
Not found modules in trainCRF.py

### ISSUE THREAD

**Issue by neda-noor-m** [dimimal/semantics_segmentation_of_urban_environments#2]
Hello
Thank you for sharing your code.
There are some modules in trainCRF.py that cannot be imported. The followings are unresolved references:

from BillinearUpsampling import BilinearUpSampling2D
from modelPredictor import computeMeanIou, plot_confusion_matrix

**Comment by dimimal** [comment]
@neda-noor-m  I am currently working on that. I am looking to update the modules in order to be easy usable for anyone.
