### ISSUE TITLE
May I ask how do you calculate the loss weight coefficients

### ISSUE THREAD

**Issue by ds-langdagu** [dimimal/semantics_segmentation_of_urban_environments#5]
Are they calculated through something like: median(list of all classes' img number)/(img number of certain class)?

**Comment by dimimal** [comment]
Compute the frequencies of all the classes. Find the median. This is your numerator. Then divide with the freq(Ci) to obtain the weight factor for the class Ci. 

W_ci = median(Freqs)/freq(Ci)

**Comment by ds-langdagu** [comment]
@dimimal thank u for ur reply
problem solved, issue closed
